<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.vgekhtman.automation</groupId>
        <artifactId>java-selenium-comparison</artifactId>
        <version>1.0-SNAPSHOT</version>
    </parent>

    <artifactId>selenium-basic</artifactId>
    <packaging>jar</packaging>

    <name>selenium-basic</name>
    <description>
        Baseline UI automation implementation using plain Selenium WebDriver, By locators
        and Page Objects, with minimal abstraction.
    </description>

    <dependencies>
        <dependency>
            <groupId>com.vgekhtman.automation</groupId>
            <artifactId>common</artifactId>
        </dependency>

        <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-java</artifactId>
        </dependency>
    </dependencies>
</project>
